/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import entidades.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.*;
/**
 *
 * @author GEORGE
 */
public class Frm_Principal extends JFrame {

    /**
     * Creates new form Frm_Menu
     */
    public Frm_Principal() {
        initComponents();
        changeColor();
    }
    
    public Frm_Principal(JFrame frm, Persona dueño, Hotel hotel) {
        initComponents();
        setLocationRelativeTo(frm);
        changeColor();
        
        this.hotel = hotel;
        this.dueño = dueño;
    }
    
    public Frm_Principal(JFrame frm,Hotel hotel, Persona dueño, Reserva registro){
        initComponents();
        setLocationRelativeTo(frm);
        changeColor();
        
        this.hotel = hotel;
        this.dueño = dueño;
        this.registro = registro;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menu = new javax.swing.JPanel();
        lbl_tituloMenu = new javax.swing.JLabel();
        btn_registro = new javax.swing.JButton();
        btn_busqueda = new javax.swing.JButton();
        btn_disponibilidad = new javax.swing.JButton();
        btn_factura = new javax.swing.JButton();
        panel_datosHotel = new javax.swing.JPanel();
        lbl_dueño = new javax.swing.JLabel();
        lbl_tituloHotel = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        btn_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panel_menu.setForeground(new java.awt.Color(51, 51, 51));

        lbl_tituloMenu.setBackground(new java.awt.Color(0, 0, 0));
        lbl_tituloMenu.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_tituloMenu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloMenu.setText("MENU");

        btn_registro.setText("<html><p>Registrar</p><p>Habitación</p></html>");
        btn_registro.setBorderPainted(false);
        btn_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registroActionPerformed(evt);
            }
        });

        btn_busqueda.setText("<html><p>Herramientas</p><p>de Busqueda</p></html>");
        btn_busqueda.setBorderPainted(false);
        btn_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedaActionPerformed(evt);
            }
        });

        btn_disponibilidad.setText("<html><p>Disponibilidad</p><p>de Habitaciones</p></html>");
        btn_disponibilidad.setActionCommand("<html><p>Verificar Disponibilidad</p><p>de Habitaciones</p></html>");
        btn_disponibilidad.setBorderPainted(false);
        btn_disponibilidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btn_factura.setText("<html><p>Generar Boleta</p><p>o Factura</p></html>");
        btn_factura.setBorderPainted(false);
        btn_factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_disponibilidad)
                            .addComponent(btn_registro))
                        .addGap(56, 56, 56)
                        .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_menuLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lbl_tituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addComponent(lbl_tituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_disponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_factura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        lbl_dueño.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        lbl_dueño.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbl_tituloHotel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lbl_tituloHotel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panel_datosHotelLayout = new javax.swing.GroupLayout(panel_datosHotel);
        panel_datosHotel.setLayout(panel_datosHotelLayout);
        panel_datosHotelLayout.setHorizontalGroup(
            panel_datosHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datosHotelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_dueño, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panel_datosHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosHotelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_tituloHotel, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panel_datosHotelLayout.setVerticalGroup(
            panel_datosHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datosHotelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lbl_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(panel_datosHotelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datosHotelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(lbl_tituloHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );

        btn_salir.setText("SALIR");
        btn_salir.setBorderPainted(false);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_info.setText("INFO");
        btn_info.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(panel_datosHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_info)
                    .addComponent(btn_salir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_datosHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btn_info, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registroActionPerformed
        Frm_Registro registro = new Frm_Registro(this, hotel, dueño);
        registro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_registroActionPerformed

    private void btn_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_busquedaActionPerformed

    private void btn_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_facturaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        lbl_tituloHotel.setText(hotel.getNombre_hotel());
        lbl_dueño.setText(dueño.getApellidos()+", "+dueño.getNombre());
    }//GEN-LAST:event_formWindowOpened

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void changeColor(){
        this.getContentPane().setBackground(new Color(64,64,64));
        panel_menu.setBackground(new Color(110,110,110));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Principal().setVisible(true);
            }
        });
    }
    
    private Hotel hotel;
    private Persona dueño;
    private Reserva registro;
    
    private ArrayList <entidades.Hotel.Piso> pisos = new ArrayList<>();
    private ArrayList <Habitacion> habitaciones = new ArrayList<>();
    private ArrayList <Cliente> huespedes = new ArrayList<>();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busqueda;
    private javax.swing.JButton btn_disponibilidad;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_registro;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_dueño;
    private javax.swing.JLabel lbl_tituloHotel;
    private javax.swing.JLabel lbl_tituloMenu;
    private javax.swing.JPanel panel_datosHotel;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
