/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import entidades.*;
import java.awt.Color;
import javax.swing.JFrame;
import java.util.*;
import entidades.habitaciones.*;
/**
 *
 * @author GEORGE
 */
public class Frm_Registro extends JFrame {

    /**
     * Creates new form Frm_Registro
     */
    public Frm_Registro() {
        initComponents();
    }

    public Frm_Registro(JFrame frm,Hotel hotel, Persona dueño) {
        initComponents();
        setLocationRelativeTo(frm);
        panel_Registro.setBackground(new Color(64,64,64));
        
        this.hotel = hotel;
        this.dueño = dueño;
    }
    
    public Frm_Registro (JFrame frm,Hotel hotel, Persona dueño, Reserva registro){
        initComponents();
        setLocationRelativeTo(frm);
        panel_Registro.setBackground(new Color(64,64,64));
        
        this.hotel = hotel;
        this.dueño = dueño;
        this.registro = registro;
    }
    
    public Frm_Registro(JFrame frm, Hotel hotel, Persona dueño, ArrayList<Cliente> huespedes,boolean estado){
        initComponents();
        setLocationRelativeTo(frm);
        panel_Registro.setBackground(new Color(64,64,64));
        
        this.hotel = hotel;
        this.dueño = dueño;
        this.huespedes = huespedes;
        
        this.setVisible(estado);
    
    }
    
    
    public Frm_Registro(JFrame frm, Hotel hotel, Persona dueño, ArrayList<Cliente> huespedes,boolean estado, Object servicio){
         initComponents();
        setLocationRelativeTo(frm);
        panel_Registro.setBackground(new Color(64,64,64));
        
        this.hotel = hotel;
        this.dueño = dueño;
        this.huespedes = huespedes;
        
        this.setVisible(estado);
        this.servicios.add(servicio);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Registro = new javax.swing.JPanel();
        lbl_Titulo = new javax.swing.JLabel();
        btn_inicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        panel_datos1 = new javax.swing.JPanel();
        lbl_numeroH = new javax.swing.JLabel();
        txt_numeroH = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btn_verificar = new javax.swing.JButton();
        txt_estadoHabitacion = new javax.swing.JTextField();
        lbl_tipo = new javax.swing.JLabel();
        cbox_tipos = new javax.swing.JComboBox<>();
        lbl_piso = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        cbox_pisos = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_fecha = new javax.swing.JLabel();
        jdc_fecha = new com.toedter.calendar.JDateChooser();
        panel_datos2 = new javax.swing.JPanel();
        lbl_numeroHuespedes = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        cbox_numeroHuespedes = new javax.swing.JComboBox<>();
        btn_registrarHuespedes = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        lbl_serviciosA = new javax.swing.JLabel();
        checkB_Restaurante = new javax.swing.JCheckBox();
        checkB_Lavanderia = new javax.swing.JCheckBox();
        jSeparator7 = new javax.swing.JSeparator();
        btn_serviciosA = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        lbl_pNoche = new javax.swing.JLabel();
        txt_precioN = new javax.swing.JTextField();
        btn_finalizarR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel_Registro.setBackground(new java.awt.Color(51, 51, 51));

        lbl_Titulo.setBackground(new java.awt.Color(51, 78, 109));
        lbl_Titulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo.setText("Registro de Habitacion");

        btn_inicio.setText("Inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbl_numeroH.setText("Numero de Habitación");

        btn_verificar.setText("Verificar Disponibilidad");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        txt_estadoHabitacion.setEditable(false);
        txt_estadoHabitacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_estadoHabitacion.setOpaque(false);

        lbl_tipo.setText("Tipo");
        lbl_tipo.setEnabled(false);

        cbox_tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Simple", "Doble", "Triple", "Matrimonial" }));
        cbox_tipos.setEnabled(false);

        lbl_piso.setText("Piso");
        lbl_piso.setEnabled(false);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbox_pisos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cbox_pisos.setEnabled(false);

        lbl_fecha.setText("Fecha");
        lbl_fecha.setEnabled(false);

        jdc_fecha.setEnabled(false);

        javax.swing.GroupLayout panel_datos1Layout = new javax.swing.GroupLayout(panel_datos1);
        panel_datos1.setLayout(panel_datos1Layout);
        panel_datos1Layout.setHorizontalGroup(
            panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos1Layout.createSequentialGroup()
                .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(panel_datos1Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos1Layout.createSequentialGroup()
                        .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btn_verificar)
                                .addGap(35, 35, 35)
                                .addComponent(txt_estadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lbl_numeroH, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(txt_numeroH, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_datos1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbl_tipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(lbl_piso)
                                .addGap(29, 29, 29)
                                .addComponent(cbox_pisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
            .addGroup(panel_datos1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lbl_fecha)
                .addGap(41, 41, 41)
                .addComponent(jdc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_datos1Layout.setVerticalGroup(
            panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_numeroH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_numeroH))
                .addGap(25, 25, 25)
                .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_verificar)
                    .addComponent(txt_estadoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tipo)
                            .addComponent(cbox_tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_piso)
                            .addComponent(cbox_pisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_datos1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(panel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jdc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_numeroHuespedes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_numeroHuespedes.setText("Numero de Huespedes");
        lbl_numeroHuespedes.setEnabled(false);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cbox_numeroHuespedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        cbox_numeroHuespedes.setEnabled(false);

        btn_registrarHuespedes.setText("<html><p> Registrar</p><p>Huespedes</p></html>");
        btn_registrarHuespedes.setEnabled(false);
        btn_registrarHuespedes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registrarHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarHuespedesActionPerformed(evt);
            }
        });

        lbl_serviciosA.setText("Servicios Adicionales");
        lbl_serviciosA.setEnabled(false);

        checkB_Restaurante.setText("Restaurante");

        checkB_Lavanderia.setText("Lavanderia");

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btn_serviciosA.setText("<html><p> Registrar</p><p>Servicios</p></html>");
        btn_serviciosA.setEnabled(false);
        btn_serviciosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_serviciosAActionPerformed(evt);
            }
        });

        lbl_pNoche.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_pNoche.setText("Precio por noche");
        lbl_pNoche.setEnabled(false);

        txt_precioN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_precioN.setEnabled(false);

        btn_finalizarR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btn_finalizarR.setText("REGISTRAR");
        btn_finalizarR.setEnabled(false);
        btn_finalizarR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finalizarRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_datos2Layout = new javax.swing.GroupLayout(panel_datos2);
        panel_datos2.setLayout(panel_datos2Layout);
        panel_datos2Layout.setHorizontalGroup(
            panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos2Layout.createSequentialGroup()
                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_datos2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbl_numeroHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cbox_numeroHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)))
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_registrarHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_serviciosA, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_datos2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(checkB_Lavanderia)
                                    .addComponent(checkB_Restaurante))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_serviciosA, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                                .addComponent(lbl_pNoche)
                                .addGap(16, 16, 16))
                            .addComponent(txt_precioN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_finalizarR, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );
        panel_datos2Layout.setVerticalGroup(
            panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_datos2Layout.createSequentialGroup()
                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_numeroHuespedes)
                        .addGap(18, 18, 18)
                        .addComponent(cbox_numeroHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_datos2Layout.createSequentialGroup()
                                .addComponent(btn_registrarHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)))))
                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_datos2Layout.createSequentialGroup()
                                .addComponent(lbl_serviciosA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkB_Restaurante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkB_Lavanderia))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btn_serviciosA, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_datos2Layout.createSequentialGroup()
                        .addComponent(lbl_pNoche)
                        .addGap(18, 18, 18)
                        .addComponent(txt_precioN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_finalizarR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(panel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_datos2Layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panel_RegistroLayout = new javax.swing.GroupLayout(panel_Registro);
        panel_Registro.setLayout(panel_RegistroLayout);
        panel_RegistroLayout.setHorizontalGroup(
            panel_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_RegistroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_RegistroLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(panel_datos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_datos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        panel_RegistroLayout.setVerticalGroup(
            panel_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_RegistroLayout.createSequentialGroup()
                .addGroup(panel_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(panel_RegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addComponent(panel_datos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_datos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        
        Frm_Principal frm_pincipal = new Frm_Principal(this, dueño, hotel);
        frm_pincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        // ARREGLAR METODO
        String numeroH = txt_numeroH.getText();
        boolean estado = comprobarNumeroH(numeroH);
        activarBotones(estado);
        
        if(estado) {
            
            txt_estadoHabitacion.setText("DISPONIBLE");
            txt_estadoHabitacion.setBackground(Color.green);
            txt_estadoHabitacion.setForeground(Color.black);
            
        }
        else {
            txt_estadoHabitacion.setText("OCUPADO");
            txt_estadoHabitacion.setBackground(Color.red);
            txt_estadoHabitacion.setForeground(Color.black);
        }
             
    }//GEN-LAST:event_btn_verificarActionPerformed
    
    private void crearRegistroHuespedes(boolean estado){
        Frm_Rhuespedes frm_huespedes = new Frm_Rhuespedes(this, dueño, hotel, (byte)(cbox_numeroHuespedes.getSelectedIndex()+1),estado);
        frm_huespedes.setVisible(true);
        frm_huespedes.setAlwaysOnTop(true);
        this.dispose();
    }
    
    private void btn_registrarHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarHuespedesActionPerformed
        int cont=cbox_numeroHuespedes.getSelectedIndex()+1;
        
        for(int i=cont;i>1;i--){
            
            crearRegistroHuespedes(false);
            
            if(i==2){
                Frm_Rhuespedes frm_huespedes = new Frm_Rhuespedes(this, dueño, hotel, (byte)(cbox_numeroHuespedes.getSelectedIndex()+1),true);
                frm_huespedes.setVisible(true);
                frm_huespedes.setAlwaysOnTop(true);
                frm_huespedes.btn_siguiente.setText("FINALIZAR");
                frm_huespedes.btn_siguiente.setBackground(Color.red);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_btn_registrarHuespedesActionPerformed

    private void crearServicio(String tipo, boolean estado){
        Frm_Rservicios frm_servicios = new Frm_Rservicios(this,hotel,dueño,huespedes,estado);
        if(estado==true)
            frm_servicios.btn_registrar.setText("FINALIZAR REGISTRO");
        
        frm_servicios.setVisible(true);
        frm_servicios.lbl_tipoServicio.setText(tipo);
        frm_servicios.setAlwaysOnTop(true);
    }
    
    private void btn_serviciosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_serviciosAActionPerformed
        
        if(checkB_Restaurante.isSelected() && checkB_Lavanderia.isSelected()){
            crearServicio("RESTAURANTE",false);
            crearServicio("LAVANDERIA",true);
            this.dispose();
        }else{
            if(checkB_Restaurante.isSelected() && !(checkB_Lavanderia.isSelected())){
                crearServicio("RESTAURANTE",true);this.dispose();
            }else{
                crearServicio("LAVANDERIA",true);this.dispose();
            }
        }
        
    }//GEN-LAST:event_btn_serviciosAActionPerformed

    private void btn_finalizarRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finalizarRActionPerformed
        
        String numero_hotel = txt_numeroH.getText();
        boolean disponibilidad = (txt_estadoHabitacion.equals("DISPONIBLE"))?true:false; //OBSERVACIONS
        Habitacion h;
        float precio = Float.parseFloat(txt_precioN.getText());
        int piso = cbox_pisos.getSelectedIndex()+1;
        
        int dia = jdc_fecha.getCalendar().get(Calendar.DAY_OF_MONTH);
        int mes = jdc_fecha.getCalendar().get(Calendar.MARCH);
        int año = jdc_fecha.getCalendar().get(Calendar.YEAR);
        
        Fecha fecha = new Fecha(dia,mes,año);
        
        int numero_huespedes = cbox_numeroHuespedes.getSelectedIndex()+1;
        
        // Servicios Adicionales
        
        String servicios[] = {"Restaurante","Lavanderia"};
        byte control_s;
        
        if(checkB_Restaurante.isSelected() || checkB_Lavanderia.isSelected()){
           control_s = (byte) ((checkB_Restaurante.isSelected())?0:1); 
        }else control_s = 2;
        
        //    
        
        switch (cbox_tipos.getSelectedIndex()){
            case 0 : h = new Habitacion_Simple();break;
            case 1 : h = new Habitacion_Doble();break;
            case 2 : h = new Habitacion_Triple();break;
            case 3 : h = new Habitacion_Matrimonial();break;
        }
        
        
        
        
    }//GEN-LAST:event_btn_finalizarRActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private boolean comprobarNumeroH(String numeroH){ // AGREGAR POSIBLE EXECTION
        iterador_habitaciones = habitaciones.iterator();
        boolean estado = true;
        
        while(iterador_habitaciones.hasNext() && estado){
            
            if(numeroH.compareToIgnoreCase(iterador_habitaciones.next().getNumero())!=0){
                estado =  false;
            } 
        }
        
        return estado;
    }
    
    private void activarBotones(boolean estado){
        
        lbl_tipo.setEnabled(estado);
        lbl_piso.setEnabled(estado);
        lbl_fecha.setEnabled(estado);
        lbl_numeroHuespedes.setEnabled(estado);
        lbl_serviciosA.setEnabled(estado);
        lbl_pNoche.setEnabled(estado);
        
        cbox_tipos.setEnabled(estado);
        cbox_pisos.setEnabled(estado);
        cbox_numeroHuespedes.setEnabled(estado);
        
        jdc_fecha.setEnabled(estado);
        
        btn_registrarHuespedes.setEnabled(estado);
        btn_serviciosA.setEnabled(estado);
        btn_finalizarR.setEnabled(estado);
        
        txt_precioN.setEnabled(estado);
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Registro().setVisible(true);
            }
        });
    }
    

    private Hotel hotel;
    private Persona dueño;
    private Reserva registro;
    
    private ArrayList <entidades.Hotel.Piso> pisos = new ArrayList<>();
    private ArrayList <Habitacion> habitaciones = new ArrayList<>();
    private ArrayList <Cliente> huespedes = new ArrayList<>();
    private ArrayList <Object> servicios = new ArrayList<>();
    private Iterator <Habitacion> iterador_habitaciones;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_finalizarR;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_registrarHuespedes;
    private javax.swing.JButton btn_serviciosA;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JComboBox<String> cbox_numeroHuespedes;
    private javax.swing.JComboBox<String> cbox_pisos;
    private javax.swing.JComboBox<String> cbox_tipos;
    private javax.swing.JCheckBox checkB_Lavanderia;
    private javax.swing.JCheckBox checkB_Restaurante;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private com.toedter.calendar.JDateChooser jdc_fecha;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_numeroH;
    private javax.swing.JLabel lbl_numeroHuespedes;
    private javax.swing.JLabel lbl_pNoche;
    private javax.swing.JLabel lbl_piso;
    private javax.swing.JLabel lbl_serviciosA;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JPanel panel_Registro;
    private javax.swing.JPanel panel_datos1;
    private javax.swing.JPanel panel_datos2;
    private javax.swing.JTextField txt_estadoHabitacion;
    private javax.swing.JTextField txt_numeroH;
    private javax.swing.JTextField txt_precioN;
    // End of variables declaration//GEN-END:variables
}
