/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import entidades.*;
import excepciones.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author GEORGE
 */
public class Frm_Inicio extends JFrame {
    /**
     * Creates new form Main
     */
    public Frm_Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titulo = new javax.swing.JLabel();
        lbl_datosG = new javax.swing.JLabel();
        txt_nombreHotel = new javax.swing.JTextField();
        lbl_nombreHotel = new javax.swing.JLabel();
        lbl_apellidosDueño = new javax.swing.JLabel();
        txt_apellidosDueño = new javax.swing.JTextField();
        btn_continuar = new javax.swing.JButton();
        lbl_datosDueño = new javax.swing.JLabel();
        lbl_datosHotel = new javax.swing.JLabel();
        txt_nombreDueño = new javax.swing.JTextField();
        lbl_nombreDueño = new javax.swing.JLabel();
        btn_siguiente = new javax.swing.JButton();
        lbl_numeroDI = new javax.swing.JLabel();
        cbox_tiposDocumentos = new javax.swing.JComboBox<>();
        lbl_documentoIdentidad = new javax.swing.JLabel();
        txt_numeroDoc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("App Hotel ");

        lbl_datosG.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_datosG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_datosG.setText("Datos Generales");

        lbl_nombreHotel.setText("Nombre del Hotel ");

        lbl_apellidosDueño.setText("Apellidos");

        txt_apellidosDueño.setEnabled(false);

        btn_continuar.setText("Continuar");
        btn_continuar.setEnabled(false);
        btn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_continuarActionPerformed(evt);
            }
        });

        lbl_datosDueño.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_datosDueño.setText("Datos del Dueño");

        lbl_datosHotel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbl_datosHotel.setText("Datos del Hotel");

        txt_nombreDueño.setEnabled(false);

        lbl_nombreDueño.setText("Nombres");

        btn_siguiente.setText("Siguiente");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });

        lbl_numeroDI.setText("Numero");

        cbox_tiposDocumentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnet de Extranjeria", "DNI", "Pasaporte", "RUC" }));
        cbox_tiposDocumentos.setEnabled(false);
        cbox_tiposDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_tiposDocumentosActionPerformed(evt);
            }
        });

        lbl_documentoIdentidad.setText("Documento de Identidad");

        txt_numeroDoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numeroDoc.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_datosG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(txt_nombreHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lbl_datosHotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_datosDueño)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lbl_nombreHotel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_nombreDueño)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_nombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_apellidosDueño)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txt_apellidosDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbox_tiposDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_numeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_documentoIdentidad)
                        .addGap(76, 76, 76)
                        .addComponent(lbl_numeroDI)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbl_datosG, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_datosDueño)
                    .addComponent(lbl_datosHotel))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidosDueño)
                    .addComponent(txt_apellidosDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nombreHotel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_nombreDueño)
                        .addComponent(txt_nombreDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_nombreHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_documentoIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(cbox_tiposDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_numeroDI, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_numeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45)
                .addComponent(btn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_continuarActionPerformed
  
        // Datos del Hotel
        String nombre_hotel = txt_nombreHotel.getText();
        
        // Datos del dueño
        String nombre = txt_nombreDueño.getText();
        String apellidos = txt_apellidosDueño.getText();
        
        // datos para el Doc. de identidad
        byte index_doc = (byte)(cbox_tiposDocumentos.getSelectedIndex());
        String numero_doc = txt_numeroDoc.getText();

        Doc_Identidad doc_i = new Doc_Identidad(numero_doc, index_doc);
        
        dueño = new Persona(nombre, apellidos, doc_i);

        hotel.setDueño(dueño);
        hotel.setNombre_hotel(nombre_hotel);
        
        if(verificarDocNumero()){
            
            Frm_Principal menu = new Frm_Principal(this, dueño, hotel);
            menu.setVisible(true);
            this.dispose();
            
        }else{
            
            txt_numeroDoc.setText(null);
            
            JOptionPane.showMessageDialog(this,"El numero del documento de identidad"
                    + " No es valido"+"\n        Digite nuevamente","Numero Incorrepto",JOptionPane.WARNING_MESSAGE);
            
        }
 
    }//GEN-LAST:event_btn_continuarActionPerformed
    
    private boolean verificarDocNumero(){
        
        float numero;
        
        try {
            
            numero = Float.parseFloat(txt_numeroDoc.getText());
            return true;
          
        } catch (NumberFormatException e) {
            
            return false;
        }
    }
    
//    private boolean comprobarTxt(JTextField... txt)throws CamposVaciosException{
//        // ARREGLAR METODO [CRITICO]
//        boolean estado = true;
//        
//        List <JTextField> textos = Arrays.asList(txt);
//        ArrayList <JTextField> prueba = new ArrayList<>(textos); // ACA ME QUEDE
//        Iterator <JTextField> iterador_txt = textos.iterator();
//        System.out.println(textos.get(0).getText());
//        while(iterador_txt.hasNext() && estado){
//            
//            if(iterador_txt.next().getText()==null || iterador_txt.next().getText()==""){
//                estado = false;
//            }
//            
//        }
//        if(estado==false){
//           throw new CamposVaciosException();  
//        }else{
//             return estado;
//        }
//    }
    
    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
     
//        try {
//            boolean comprobarTxt = comprobarTxt(true);
       activar_botonContinuar(true);
//        } catch (CamposVaciosException e) {
//            JOptionPane.showMessageDialog(this,e.getMessage(),e.getClass().getName(),JOptionPane.WARNING_MESSAGE);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this,ex.getMessage(),ex.getClass().getName(),JOptionPane.WARNING_MESSAGE);
//        } 
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void cbox_tiposDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_tiposDocumentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_tiposDocumentosActionPerformed
    
    private void activar_botonContinuar (boolean state){
        txt_nombreDueño.setEnabled(state);
        txt_apellidosDueño.setEnabled(state);
        cbox_tiposDocumentos.setEnabled(state);
        txt_numeroDoc.setEnabled(state);
        btn_continuar.setEnabled(state);
        btn_siguiente.setEnabled(!state);
        txt_nombreHotel.setEnabled(!state);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Inicio().setVisible(true);
            }
        });
    }

    private Persona dueño;
    private Hotel hotel = new Hotel();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_continuar;
    private javax.swing.JButton btn_siguiente;
    private javax.swing.JComboBox<String> cbox_tiposDocumentos;
    private javax.swing.JLabel lbl_apellidosDueño;
    private javax.swing.JLabel lbl_datosDueño;
    private javax.swing.JLabel lbl_datosG;
    private javax.swing.JLabel lbl_datosHotel;
    private javax.swing.JLabel lbl_documentoIdentidad;
    private javax.swing.JLabel lbl_nombreDueño;
    private javax.swing.JLabel lbl_nombreHotel;
    private javax.swing.JLabel lbl_numeroDI;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JTextField txt_apellidosDueño;
    private javax.swing.JTextField txt_nombreDueño;
    private javax.swing.JTextField txt_nombreHotel;
    private javax.swing.JTextField txt_numeroDoc;
    // End of variables declaration//GEN-END:variables
}
